name: Sync jin18.txt from GitHub to Gitee

on:
  schedule:
    - cron: "0 */2 * * *"  # 每6小时同步一次
  workflow_dispatch:       # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Download jin18.txt from remote
        run: |
          wget -O jin18.json "https://moontv.yichen.eu.org/api/tvbox/subscribe?token=ce9e99842689073cf3a3a1a854ff84f8"

      - name: Push to Gitee
        run: |
          # ========== 只改这里 ==========
          GITEE_USER="z33ss"
          GITEE_REPO="box"
          # ==============================

          git config --global user.name "Auto Sync"
          git config --global user.email "sync@github.com"

          git clone https://${GITEE_USER}:${{ secrets.GITEE_TOKEN }}@gitee.com/${GITEE_USER}/${GITEE_REPO}.git repo
          cp -f jin18.txt repo/
          cd repo
          git add jin18.txt
          git commit -m "Auto sync jin18.txt" || exit 0
          git push
